### ISSUE TITLE
Import GPS coordinates into DB

### ISSUE THREAD

**Issue by claudiughioc** [initiativaromania/HartaBanilorPublici#11]
This is quite delicate, there is a file somewhere on slack I guess with GPS coordinates for all the public institutions in the new DB. If we can't find it, we'll have to regenerate it.

**Comment by arw357** [comment]
I see that in slack you have a very powerfull search method  - I found - a file called nomenclator autoritati contractante.xlsx and "autoritati publice cu adresa". Is it one of these ?

**Comment by arw357** [comment]
I have been looking at this issue and i have a proposition. There are aprox 15000 institutions that can be shown on the map according to the file "autoritati public cu adresa". Each time a user enters the application depending on where they are there are 2 posibilities : 1 - get all the institutions in the area that the user is in and 2 - fetch all the institutions one time.  1st option requires any zooming in or out a new request to the server. This problem is multiple requests vs huge data transmission. I'm proposing a 3rd option here. We can deliver the institutions in a file with the application. The file contains id in database, coordinates and maybe another id that is used to color the marker.  Load the file on application load  with the MarkerClusterer. Thus you call the server only when you need information about a company. What's  your say ?
